-- ==========================================
-- SyncSpace AI - Supabase PostgreSQL Schema
-- ==========================================

-- Enable the pgcrypto extension for UUIDs (gen_random_uuid is built into modern Postgres, 
-- but it's good practice to ensure extension availability if using older versions or uuid_generate_v4)
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ==========================================
-- ENUMS
-- ==========================================
CREATE TYPE public.team_role AS ENUM ('owner', 'admin', 'member');
CREATE TYPE public.processing_status AS ENUM ('pending', 'processing', 'completed', 'failed');
CREATE TYPE public.action_status AS ENUM ('open', 'in_progress', 'completed', 'cancelled');
CREATE TYPE public.risk_severity AS ENUM ('low', 'medium', 'high', 'critical');

-- ==========================================
-- TABLES
-- ==========================================

-- 1. TEAMS
-- Represents workspaces or organizations within SyncSpace AI.
CREATE TABLE public.teams (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- 2. TEAM_MEMBERS
-- Junction table mapping users to teams with specific roles.
CREATE TABLE public.team_members (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    team_id UUID REFERENCES public.teams(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    role public.team_role DEFAULT 'member' NOT NULL,
    joined_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    -- Ensure a user can only be in a team once
    CONSTRAINT unique_team_user UNIQUE(team_id, user_id)
);

-- 3. MEETINGS
-- Stores core meeting data and transcript metadata.
CREATE TABLE public.meetings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    team_id UUID REFERENCES public.teams(id) ON DELETE CASCADE NOT NULL,
    uploaded_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    transcript_text TEXT,
    summary TEXT,
    uploaded_file_name TEXT,
    processing_status public.processing_status DEFAULT 'pending' NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- 4. ACTION_ITEMS
-- Extracted tasks assigned to team members.
CREATE TABLE public.action_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    meeting_id UUID REFERENCES public.meetings(id) ON DELETE CASCADE NOT NULL,
    -- NLP pipelines usually extract text names. This UUID assumes you map 
    -- the extracted name to a registered user ID before saving to DB.
    assigned_to UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    task TEXT NOT NULL,
    deadline TIMESTAMPTZ,
    status public.action_status DEFAULT 'open' NOT NULL,
    -- Store ML confidence score between 0.0 and 1.0
    confidence NUMERIC(4,3) CHECK (confidence >= 0 AND confidence <= 1),
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- 5. DECISIONS
-- Key decisions identified by the NLP pipeline.
CREATE TABLE public.decisions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    meeting_id UUID REFERENCES public.meetings(id) ON DELETE CASCADE NOT NULL,
    decision_text TEXT NOT NULL,
    category TEXT,
    confidence NUMERIC(4,3) CHECK (confidence >= 0 AND confidence <= 1),
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- 6. RISKS
-- Potential issues or risks identified in the meeting.
CREATE TABLE public.risks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    meeting_id UUID REFERENCES public.meetings(id) ON DELETE CASCADE NOT NULL,
    risk_text TEXT NOT NULL,
    severity public.risk_severity DEFAULT 'medium' NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- 7. TOPIC_CLUSTERS
-- Unsupervised topic clusters generated by HDBSCAN/UMAP.
CREATE TABLE public.topic_clusters (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    meeting_id UUID REFERENCES public.meetings(id) ON DELETE CASCADE NOT NULL,
    topic_name TEXT NOT NULL,
    coherence NUMERIC(4,3) CHECK (coherence >= 0 AND coherence <= 1),
    -- Use text array to store the associated keywords for the cluster
    keywords TEXT[] DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);


-- ==========================================
-- INDEXES FOR PERFORMANCE
-- ==========================================

-- Teams
CREATE INDEX idx_teams_created_by ON public.teams(created_by);

-- Team Members
CREATE INDEX idx_team_members_team_id ON public.team_members(team_id);
CREATE INDEX idx_team_members_user_id ON public.team_members(user_id);

-- Meetings
CREATE INDEX idx_meetings_team_id ON public.meetings(team_id);
CREATE INDEX idx_meetings_uploaded_by ON public.meetings(uploaded_by);
CREATE INDEX idx_meetings_status ON public.meetings(processing_status);

-- Action Items
CREATE INDEX idx_action_items_meeting_id ON public.action_items(meeting_id);
CREATE INDEX idx_action_items_assigned_to ON public.action_items(assigned_to);
CREATE INDEX idx_action_items_status ON public.action_items(status);

-- Decisions
CREATE INDEX idx_decisions_meeting_id ON public.decisions(meeting_id);

-- Risks
CREATE INDEX idx_risks_meeting_id ON public.risks(meeting_id);
CREATE INDEX idx_risks_severity ON public.risks(severity);

-- Topic Clusters
CREATE INDEX idx_topic_clusters_meeting_id ON public.topic_clusters(meeting_id);


-- ==========================================
-- ROW LEVEL SECURITY (RLS) SETUP
-- ==========================================
-- In Supabase, it is highly recommended to enable RLS. 
-- You will need to define explicit policies for users to read/write data.
ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.meetings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.action_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.decisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.risks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.topic_clusters ENABLE ROW LEVEL SECURITY;
